services:
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=test_app'
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_USER=test'
    network_mode: bridge
    ports:
      - '5432:5432'

  app:
    image: 'app-jar-for-k8s:latest'
    ports:
      - '8090:8090'
    depends_on:
      - db
    network_mode: bridge
    links:
      - db
